=== catalyst-engine/CEngine/src/editor/core/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="EText">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="BlockView">
        <xs:sequence>
            <xs:element name="EText" type="EText" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="EMenuItem">
        <xs:sequence>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="title" type="xs:string" use="required"/>
        <xs:attribute name="shortcut" type="xs:string"/>
        <xs:attribute name="enabled" type="xs:boolean"/>
        <xs:attribute name="checked" type="xs:boolean"/>
        <xs:attribute name="addSeparator" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="ETree">
        <xs:sequence>
            <xs:element name="ETableColumn" type="ETableColumn" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="ETableColumn">
        <xs:sequence>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string" use="required"/>
        <xs:attribute name="initWidth" type="xs:float"/>
        <xs:attribute name="noHide" type="xs:boolean"/>
        <xs:attribute name="widthFixed" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="ESection">
        <xs:sequence>
            <xs:element name="EText" type="EText" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="EMenuBar" type="EMenuBar" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="ETree" type="ETree" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="title" type="xs:string" use="required"/>

        <xs:attribute name="noTitleBar" type="xs:boolean"/>
        <xs:attribute name="noScrollbar" type="xs:boolean"/>
        <xs:attribute name="menuBar" type="xs:boolean"/>
        <xs:attribute name="noMove" type="xs:boolean"/>
        <xs:attribute name="noResize" type="xs:boolean"/>
        <xs:attribute name="noCollapse" type="xs:boolean"/>
        <xs:attribute name="noNav" type="xs:boolean"/>
        <xs:attribute name="noBackground" type="xs:boolean"/>
        <xs:attribute name="noBringToFrontOnFocus" type="xs:boolean"/>
        <xs:attribute name="noDocking" type="xs:boolean"/>
        <xs:attribute name="unsavedDocument" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="EMenu">
        <xs:sequence>
            <xs:element type="EMenuItem" name="EMenuItem" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="EMenu" name="EMenu" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="title" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="EButton">
        <xs:sequence>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string" use="required"/>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="EMenuBar">
        <xs:sequence>
            <xs:element type="EMenu" name="EMenu" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="EButton" type="EButton" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="isMainMenu" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="Body">
        <xs:sequence>
            <xs:element type="ESection" name="ESection"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Body" type="Body">
    </xs:element>
</xs:schema>

=== catalyst-engine/CEngine/src/window/editor/static/HierarchyView.xml
<?xml version='1.0' encoding='UTF-8'?>
<Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../ui/Schema.xsd"
>
    <ESection id="hierarchyContainer" title="Hierarchy" noMove="true">
        <EMenuBar isMainMenu="false">
            <EMenu title="Add">
                <EMenuItem id="hierarchyAddEmpty" title="Empty entity"/>
            </EMenu>
            <EMenu title="Select">
                <EMenuItem id="hierarchySelectAll" title="All"/>
                <EMenuItem id="hierarchySelectInvert" title="Invert selection"/>
                <EMenuItem id="hierarchySelectHierarchy" title="Hierarchy"/>
            </EMenu>
            <EButton id="hierarchyDeleteButton" title="Delete"/>
        </EMenuBar>
    </ESection>
</Body>

=== catalyst-engine/CEngine/src/window/editor/views/HierarchyView.xml
<?xml version='1.0' encoding='UTF-8'?>
<Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../ui/Schema.xsd"
>
    <ESection id="hierarchyContainer" title="Hierarchy">
        <EMenuBar>
            <EMenu title="Add">
                <EMenuItem id="hierarchyAddEmpty">
                    Empty entity
                </EMenuItem>
            </EMenu>
            <EMenu title="Select">
                <EMenuItem id="hierarchySelectAll">
                    All
                </EMenuItem>
                <EMenuItem id="hierarchySelectInvert">
                    Invert selection
                </EMenuItem>
                <EMenuItem id="hierarchySelectHierarchy">
                    Hierarchy
                </EMenuItem>
            </EMenu>
            <EButton id="hierarchyDeleteButton">
                Delete
            </EButton>
        </EMenuBar>
        <ETree id="hierarchyTree">
            <ETableColumn title="Name"/>
        </ETree>
    </ESection>
</Body>
